<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DevisTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('devis')->delete();
        
        \DB::table('devis')->insert(array (
            0 => 
            array (
                'id' => 1,
                'numero' => 'EBX_DE2012-0021',
                'lot' => 'Pose antenne',
                'chantier_id' => 1,
                'entreprise_id' => 1,
                'client_id' => 10,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 1,
                'collaborateur_id' => 1,
                'total_ht' => 336.5,
                'total_ttc' => 403.8,
                'tva' => 67.3,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-10',
                'date_envoie' => '2020-12-10',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 11:49:33',
                'updated_at' => '2020-12-18 11:49:33',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'numero' => 'EBX_DE2012-0023',
                'lot' => 'Rénovation d\'une maison',
                'chantier_id' => 15,
                'entreprise_id' => 1,
                'client_id' => 11,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 1,
                'collaborateur_id' => 3,
                'total_ht' => 7414.73,
                'total_ttc' => 7414.73,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-11',
                'date_envoie' => '2020-12-11',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 11:50:56',
                'updated_at' => '2020-12-18 11:50:56',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'numero' => 'EBX_DE2011-0011',
                'lot' => 'Rénovation d\'une échoppe',
                'chantier_id' => 8,
                'entreprise_id' => 1,
                'client_id' => 6,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 1,
                'collaborateur_id' => 3,
                'total_ht' => 16731.6,
                'total_ttc' => 18404.76,
                'tva' => 1673.16,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-10-20',
                'date_envoie' => '2020-10-20',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:13:09',
                'updated_at' => '2020-12-18 12:13:09',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'numero' => 'EBX_DE2011-0012',
                'lot' => 'Rénovation et ouverture de la cuisine',
                'chantier_id' => 13,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 1,
                'collaborateur_id' => 3,
                'total_ht' => 1416.14,
                'total_ttc' => 1416.14,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-11-20',
                'date_envoie' => '2020-11-20',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:15:05',
                'updated_at' => '2020-12-18 12:15:05',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'numero' => 'EBX_DE2011-0009',
                'lot' => 'Rénovation d\'un appartement',
                'chantier_id' => 12,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 1,
                'collaborateur_id' => 3,
                'total_ht' => 4041.08,
                'total_ttc' => 4041.08,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-11-20',
                'date_envoie' => '2020-11-20',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:16:17',
                'updated_at' => '2020-12-18 12:16:17',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'numero' => 'EBX_DE2011-0010',
                'lot' => 'Reprises cuisines',
                'chantier_id' => 5,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 782.76,
                'total_ttc' => 782.76,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-11-29',
                'date_envoie' => '2020-11-29',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:17:52',
                'updated_at' => '2020-12-18 12:17:52',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'numero' => 'EBX_DE2011-0008',
                'lot' => 'Rénovation d\'un appartement',
                'chantier_id' => 4,
                'entreprise_id' => 1,
                'client_id' => 4,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 105.0,
                'total_ttc' => 115.5,
                'tva' => 10.5,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-11-30',
                'date_envoie' => '2020-11-30',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:18:58',
                'updated_at' => '2020-12-18 12:18:58',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'numero' => 'EBX_DE2011-0007',
                'lot' => 'Mise en sécurité',
                'chantier_id' => 13,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 50.0,
                'total_ttc' => 50.0,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-11-30',
                'date_envoie' => '2020-11-30',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:20:22',
                'updated_at' => '2020-12-18 12:20:22',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'numero' => 'EBX_DE2011-0002',
                'lot' => 'Rénovation d\'un appartement',
                'chantier_id' => 9,
                'entreprise_id' => 1,
                'client_id' => 3,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 1,
                'collaborateur_id' => 3,
                'total_ht' => 2069.42,
                'total_ttc' => 2276.36,
                'tva' => 206.94,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-11-30',
                'date_envoie' => '2020-11-30',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:22:01',
                'updated_at' => '2020-12-18 12:22:01',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'numero' => 'EBX_DE2011-0001',
                'lot' => '29 Rue traversanne bordeaux',
                'chantier_id' => 14,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 90.0,
                'total_ttc' => 90.0,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-11-30',
                'date_envoie' => '2020-11-30',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:23:19',
                'updated_at' => '2020-12-18 12:23:19',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'numero' => 'EBX_DE2012-0019',
                'lot' => 'Mise en sécurité',
                'chantier_id' => 12,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 523.0,
                'total_ttc' => 523.0,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-04',
                'date_envoie' => '2020-12-04',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:25:19',
                'updated_at' => '2020-12-18 12:25:19',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'numero' => 'EBX_DE2012-0018',
                'lot' => 'Mise en sécurité',
                'chantier_id' => 13,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 50.0,
                'total_ttc' => 50.0,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-04',
                'date_envoie' => '2020-12-04',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:29:16',
                'updated_at' => '2020-12-18 12:29:16',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'numero' => 'EBX_DE2012-0017',
                'lot' => 'Ajout PC chambres enfants',
                'chantier_id' => 6,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 225.18,
                'total_ttc' => 225.18,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-04',
                'date_envoie' => '2020-12-04',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:30:37',
                'updated_at' => '2020-12-18 12:30:37',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'numero' => 'EBX_DE2001-0044',
                'lot' => 'Pose d\'un détecteur domotique',
                'chantier_id' => 2,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 150.0,
                'total_ttc' => 150.0,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-04',
                'date_envoie' => '2020-12-04',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:31:51',
                'updated_at' => '2020-12-18 12:31:51',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'numero' => 'EBX_DE2012-0014',
                'lot' => 'Dépose VMC',
                'chantier_id' => 6,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 366.94,
                'total_ttc' => 366.94,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-04',
                'date_envoie' => '2020-12-04',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:32:56',
                'updated_at' => '2020-12-18 12:32:56',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'numero' => 'EBX_DE2012-0013',
                'lot' => 'Dépose de goulotte',
                'chantier_id' => 10,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 1,
                'collaborateur_id' => 1,
                'total_ht' => 200.0,
                'total_ttc' => 200.0,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-04',
                'date_envoie' => '2020-12-04',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:34:06',
                'updated_at' => '2020-12-18 12:34:06',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'numero' => 'EBX_DE2012-0022',
                'lot' => 'Pose trappe accés',
                'chantier_id' => 12,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 55.4,
                'total_ttc' => 55.4,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-06',
                'date_envoie' => '2020-12-06',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:35:18',
                'updated_at' => '2020-12-18 12:35:18',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'numero' => 'EBX_DE2012-0025',
                'lot' => 'VDI - Garage',
                'chantier_id' => 2,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 106.4,
                'total_ttc' => 106.4,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-17',
                'date_envoie' => '2020-12-17',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:38:29',
                'updated_at' => '2020-12-18 12:38:29',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'numero' => 'EBX_DE2012-0024',
                'lot' => 'Piquage Sol + Renouvellement Tableau',
                'chantier_id' => 12,
                'entreprise_id' => 1,
                'client_id' => 1,
                'bilan_id' => NULL,
                'etat_devi_id' => 1,
                'type_devi_id' => 2,
                'collaborateur_id' => 1,
                'total_ht' => 155.0,
                'total_ttc' => 155.0,
                'tva' => 0.0,
                'progbox_sauve' => NULL,
                'date_creation' => '2020-12-17',
                'date_envoie' => '2020-12-17',
                'date_signature' => NULL,
                'created_at' => '2020-12-18 12:40:19',
                'updated_at' => '2020-12-18 12:40:19',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}